---
title: "Section 2"
author: "Or Caspi"
date: "10/9/2020"
output: html_document
---
### Import databases
```{r}
census <- read.csv("c:/Users/Or Laptop/Downloads/2010+Census+Population+By+Zipcode+(ZCTA).csv")
permits <- read.csv("c:/Users/Or Laptop/Downloads/Historical_DOB_Permit_Issuance.csv")
```

### Question 1
```{r}
nrow(permits[which(permits$Filing.Status=="RENEWAL"),])/nrow(permits)
```

### Question 2
```{r}
renewd <- permits[which(permits$Filing.Status=="RENEWAL"),]
nrow(renewd[which(renewd$Owner.s.Business.Type=="CORPORATION"),])/nrow(renewd[which(renewd$Owner.s.Business.Type=="INDIVIDUAL"),])
```

### Question 3:
```{r}
library(dplyr)

permits$start_date <- substr(permits$Issuance.Date, 1, 10)
permits$start_date <- as.Date(permits$start_date)
permits$end_date <- substr(permits$Expiration.Date, 1, 10)
permits$end_date <- as.Date(permits$end_date)
permits$days <- permits$end_date - permits$start_date
year <- permits[which(permits$days>365),]

by_borough <- group_by(year, BOROUGH)
by_borough <- summarise(by_borough, n=n())

by_borough[[which(by_borough$n==max(by_borough$n)),2]]/sum(by_borough$n)
```

### Question 4:
```{r}
permits$fill_date <- substr(permits$Filing.Date, 1, 10)
permits$fill_date <- as.Date(permits$fill_date)
fill2010 <- permits[which(permits$fill_date >= as.Date("2010-01-01") & permits$fill_date < as.Date("2011-01-01")),]
issue2010 <- permits[which(fill2010$start_date >= as.Date("2010-01-01") & fill2010$start_date < as.Date("2011-01-01")),]

by_zip <- group_by(issue2010, Postcode)
by_zip <- summarise(by_zip, n=n())
by_zip <- merge(by_zip, census, by.x="Postcode", by.y="Zip.Code.ZCTA")
by_zip <- by_zip[which(by_zip$X2010.Census.Population > 999),]
by_zip$ratio <- by_zip$n/by_zip$X2010.Census.Population

length(which(by_zip$ratio>(2*sd(by_zip$ratio)+mean(by_zip$ratio)) | by_zip$ratio<(mean(by_zip$ratio)-2*sd(by_zip$ratio))))
```

### Question 5:
```{r}
permits$issue_year <- as.integer(substr(permits$Issuance.Date, 1, 4))
by_year <- group_by(permits[which(permits$issue_year>=1990 & permits$issue_year<=2012),], issue_year)
by_year <- summarise(by_year, n=n())

r2 <- lm(issue_year ~ n, data=by_year)
summary(r2)$r.squared
```

### Question 6:
```{r}
permits$job_year <- as.integer(substr(permits$Job.Start.Date, 1, 4))
permits$job_month <- as.integer(substr(permits$Job.Start.Date, 6, 7))
permits$winter <- 0
permits[which(permits$job_month<3),"winter"] <- 1
permits$summer <- 0
permits[which(permits$job_month==7 | permits$job_month==8),"summer"] <- 1

by_job <- group_by(permits[which(permits$job_year>=1990 & permits$job_year<=2012),], job_year)
by_job <- summarise(by_job, summer=sum(summer), winter=sum(winter))
by_job$ratio <- by_job$summer / by_job$winter

max(by_job$ratio)
```

### Question 7:
```{r}
sixty <- permits[which(permits$days<60),]
sixty$nov <- 0
sixty[which(sixty$job_month==11),"nov"] <- 1

by60 <- group_by(sixty[which(sixty$job_year>=1990 & sixty$job_year<=2012),], job_year)
by60 <- summarise(by60, jobs=n(), nov=sum(nov))
by60$other <- round((by60$jobs - by60$nov)/11,0)

chisq.test(x=by60$nov,y=by60$other)
```